#ifndef __VIEW09_SELF_CLEANING_MODE_H_
#define __VIEW09_SELF_CLEANING_MODE_H_

typedef enum {
	VIEW09_SELF_CLEANING_MODE_NULL,
	VIEW09_SELF_CLEANING_MODE_LABEL9_ID = 16,
	VIEW09_SELF_CLEANING_MODE_LABEL7_ID = 14,
	VIEW09_SELF_CLEANING_MODE_LABEL8_ID = 15,
	VIEW09_SELF_CLEANING_MODE_LABEL3_ID = 8,
	VIEW09_SELF_CLEANING_MODE_IMAGE6_ID = 17,
	VIEW09_SELF_CLEANING_MODE_LABEL4_ID = 9,
	VIEW09_SELF_CLEANING_MODE_LABEL6_ID = 13,
	VIEW09_SELF_CLEANING_MODE_LABEL5_ID = 12,
	VIEW09_SELF_CLEANING_MODE_LABEL2_ID = 7,
	VIEW09_SELF_CLEANING_MODE_LABEL0_ID = 1,
	VIEW09_SELF_CLEANING_MODE_LABEL1_ID = 6,
	VIEW09_SELF_CLEANING_MODE_IMAGE4_ID = 10,
	VIEW09_SELF_CLEANING_MODE_LABEL10_ID = 18,
	VIEW09_SELF_CLEANING_MODE_IMAGE5_ID = 11,
	VIEW09_SELF_CLEANING_MODE_IMAGE3_ID = 5,
	VIEW09_SELF_CLEANING_MODE_IMAGE0_ID = 2,
	VIEW09_SELF_CLEANING_MODE_IMAGE1_ID = 3,
	VIEW09_SELF_CLEANING_MODE_IMAGE2_ID = 4
} view09_self_cleaning_mode_ctrls_id_e;

void view09_self_cleaning_mode_init(void);
void view09_self_cleaning_mode_entry(void);
void view09_self_cleaning_mode_exit(void);

#endif
