static grf_view_fun_t grf_views_fun[] = {
	{GRF_VIEW01_ID,view01_init,view01_entry,view01_exit},
	{GRF_VIEW02_CLEANING_ID,view02_cleaning_init,view02_cleaning_entry,view02_cleaning_exit},
	{GRF_VIEW03_VOICE_ICON_ID,view03_voice_icon_init,view03_voice_icon_entry,view03_voice_icon_exit},
	{GRF_VIEW04_BATTERY_WATER_ID,view04_battery_water_init,view04_battery_water_entry,view04_battery_water_exit},
	{GRF_VIEW05_STERILIZATION_FLUID_PREPARATION_ID,view05_sterilization_fluid_preparation_init,view05_sterilization_fluid_preparation_entry,view05_sterilization_fluid_preparation_exit},
	{GRF_VIEW06_STERILIZATION_ID,view06_sterilization_init,view06_sterilization_entry,view06_sterilization_exit},
	{GRF_VIEW07_WATER_SUCTION_ID,view07_water_suction_init,view07_water_suction_entry,view07_water_suction_exit},
	{GRF_VIEW08_CHARGING_ID,view08_charging_init,view08_charging_entry,view08_charging_exit},
	{GRF_VIEW09_SELF_CLEANING_MODE_ID,view09_self_cleaning_mode_init,view09_self_cleaning_mode_entry,view09_self_cleaning_mode_exit},
	{GRF_VIEW10_SELF_CLEANING_ID,view10_self_cleaning_init,view10_self_cleaning_entry,view10_self_cleaning_exit},
	{GRF_VIEW11_FAULT_ID,view11_fault_init,view11_fault_entry,view11_fault_exit},
	{GRF_VIEW10_01_PLEASE_CLEAN_THE_DIRTY_WATER_TANK_ID,view10_01_please_clean_the_dirty_water_tank_init,view10_01_please_clean_the_dirty_water_tank_entry,view10_01_please_clean_the_dirty_water_tank_exit},
	{GRF_VIEW12_HELP_ID,view12_help_init,view12_help_entry,view12_help_exit},
	{GRF_VIEW13_HELP1_ID,view13_help1_init,view13_help1_entry,view13_help1_exit},
	{GRF_VIEW14_HELP2_ID,view14_help2_init,view14_help2_entry,view14_help2_exit},
	{GRF_VIEW15_HELP3_ID,view15_help3_init,view15_help3_entry,view15_help3_exit},
	{GRF_VIEW16_HELP4_ID,view16_help4_init,view16_help4_entry,view16_help4_exit},
	{GRF_VIEW17_SYSTEM_SETTING_ID,view17_system_setting_init,view17_system_setting_entry,view17_system_setting_exit},
	{GRF_VIEW18_ENGINEERING_TEST_MODE_ID,view18_engineering_test_mode_init,view18_engineering_test_mode_entry,view18_engineering_test_mode_exit},
	{GRF_VIEW19_RESTORE_FACTORY_SETTINGS_ID,view19_restore_factory_settings_init,view19_restore_factory_settings_entry,view19_restore_factory_settings_exit},
	{GRF_VIEW20_LOGO_ID,view20_logo_init,view20_logo_entry,view20_logo_exit}
};

