static grf_ctrl_fun_t view_ctrls_fun_t[] =
{
	{VIEW17_SYSTEM_SETTING_LABEL4_ID,label4_event},
	{VIEW17_SYSTEM_SETTING_LABEL5_ID,label5_event},
	{VIEW17_SYSTEM_SETTING_IMAGE4_ID,image4_event},
	{VIEW17_SYSTEM_SETTING_CONTAINER0_ID,container0_event},
	{VIEW17_SYSTEM_SETTING_LABEL0_ID,label0_event},
	{VIEW17_SYSTEM_SETTING_IMAGE1_ID,image1_event},
	{VIEW17_SYSTEM_SETTING_LABEL1_ID,label1_event},
	{VIEW17_SYSTEM_SETTING_IMAGE2_ID,image2_event},
	{VIEW17_SYSTEM_SETTING_LABEL2_ID,label2_event},
	{VIEW17_SYSTEM_SETTING_IMAGE0_ID,image0_event},
	{VIEW17_SYSTEM_SETTING_LABEL3_ID,label3_event}
};